### ISSUE TITLE
Setting does not work

### ISSUE THREAD

**Issue by thomasmoors** [sinergi/config#10]
```
$cnf = Sinergi\Config\Collection::factory(['path' => '../config', 'dotenv' => '/']);

echo $cnf->get('fake.username'); //admin
$cnf->set('fake.username', 'new');
echo $cnf->get('fake.username'); //admin
```

**Comment by gabrielbull** [comment]
Hi @thomasmoors,

I am no longer going to maintain this package, if you are interested I can transfer it to you.

Gabriel

**Comment by thomasmoors** [comment]
Sorry, but I'm not interested right now. I'm working on my thesis and other things. So no time to maintain an open source project right now. Good luck and thanks for a nice package.
